apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}
  description: PostgreSQL Database Instance
  tags: [postgres, database, infrastructure]
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  owner: ${{ values.owner }}
  system: infrastructure
