apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nats-messaging
  title: NATS Server (Infrastructure)
  description: Provision a NATS Server
  tags: [infrastructure, nats, messaging]
spec:
  owner: user:guest
  type: resource

  parameters:
    - title: NATS Configuration
      required: [name, owner]
      properties:
        name:
          title: Server Name
          type: string
        owner:
          title: Owner
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group, User]

    - title: Repository Location
      required: [repoUrl]
      properties:
        repoUrl:
          title: Repository Location
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]
            allowedOwners: [homedevlabs]
            defaultOwner: homedevlabs
          type: string

  steps:
    - id: fetch-base
      name: Fetching Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publishing to GitHub
      action: publish:github
      input:
        description: NATS server for ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: register
      name: Registering in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
