apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: elasticsearch
  title: ElasticSearch (Infrastructure)
  description: Provision an ElasticSearch Cluster (Single Node)
  tags:
    - infrastructure
    - elasticsearch
    - logging
spec:
  owner: user:guest
  type: resource

  parameters:
    - title: ElasticSearch Configuration
      required:
        - name
        - owner
      properties:
        name:
          title: Cluster Name
          type: string
          description: Unique name for the ES cluster (e.g. logs-es)
        owner:
          title: Owner
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group, User]
        memory:
          title: Heap Size (Java)
          type: string
          default: 512m
          enum:
            - 512m
            - 1g
            - 2g

    - title: Repository Location
      required: [repoUrl]
      properties:
        repoUrl:
          title: Repository Location
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - homedevlabs
            defaultOwner: homedevlabs
          type: string

  steps:
    - id: fetch-base
      name: Fetching Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          memory: ${{ parameters.memory }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publishing to GitHub
      action: publish:github
      input:
        description: Infrastructure provisioning for ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: register
      name: Registering in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
